locale: en
time-format: "dd/MM/yyyy HH:mm:ss"
main:
  update:
    check: true
    auto: false
whitelist:
  status: false # Is whitelist enabled
  mode: OFFLINE # ONLINE - use only license uuid's to check player access / OFFLINE - use only non-license uuid's to check player access
  remove-on-expired: false # Is delete player from database on join when he's time is expired
  kick-on-remove: false # Is kick player from server when remove he from whitelist with command
  bypass:
    permission: # Permission to bypass whitelist join restrictions
      enabled: false # Is this permission enabled
      permission: mwl.join.restrict.bypass # Anyone with this permission will be able to enter the server regardless of whether it is on the white list
  player-check: # Checks if the player is on the whitelist and if he still has time, if not, then kicks the player
    enabled: false # Is players check enabled
    initial-delay: 0 # Timer initial delay in milliseconds
    delay: 60000 # Timer delay in milliseconds
database:
  type: JSON # Database type (JSON, MONGO)
  mongodb: # MongoDB settings
    url: "mongodb://admin:admin@127.0.0.1/mwl" # Connection url
    name: "mwl" # Database name
    collections: # Collections name's
      users: "users" # Users collection