name: mWL
version: '${version}'
main: me.truec0der.mwhitelist.MWhitelist
api-version: '1.18'
load: STARTUP
authors: [ TRUEC0DER ]
description: Server whitelist using MongoDB
website: https://github.com/TRUEC0DER
libraries:
  - org.mongodb:mongodb-driver-sync:4.11.1
commands:
  mwhitelist:
    description: "UUID-based server whitelist using MongoDB and more"
    aliases: [ mwl ]
